/** @format */

export const API_ROUTE = {
    LOGIN: "/auth/login",
    LOGOUT: "/auth/logout",
    SIGNUP: "/auth/register",
    GOOGLE: "/auth/google",
    FORGOT_PASSWORD: "/auth/forgot-password",
    REFRESH_TOKEN: "/auth/refresh-token",
    VERIFY_RP_TOKEN: "/auth/validation-recovery-password-token",
    RESET_PASSWORD_BY_RP_TOKEN: "/auth/recovery-password",

    CREATE_PRODUCT: "/product/create",
    GET_PRODUCTS: "/product/get-products",
    GET_PRODUCT_DETAILS: "/product/get-product-details",
    UPDATE_PRODUCT: "/product/update",
    DELETE_PRODUCT: "/product/delete",
    GET_PRODUCT_COUNT_BY_SPORT: "/product/get-sport-type",
    GET_TOP_SALE_PRODUCT: "/product/get-top-sale",
    GET_TOP_SALE_PRODUCT_BY_GENDER: "/product/get-top-sale-by-gender",
    GET_BEST_SELLER: "/product/get-best-seller",
    ADD_FAVORITE_PRODUCT: "/product/add-favorite",
    REMOVE_FAVORITE_PRODUCT: "/product/remove-favorite",
    GET_FAVORITE_PRODUCTS: "/product/get-favorite-products",
    GET_PRODUCT_LIST_BY_ID: "/product/get-list-by-id",
    GET_PRODUCT_BY_NAME: "/product/get-by-name",
    GET_PRODUCT_BY_SEARCH: "/product/get-by-search",

    GET_ALL_CUSTOMERS: "/user/get-all-customers",
    UPDATE_CUSTOMER_STATUS: "/user/update-customer-status",
    DELETE_CUSTOMER: "/user/delete-customer",
    ADMIN_UPDATE_INFO: "/user/admin-update-info",
    ADMIN_UPDATE_PASSWORD: "/user/admin-update-password",
    USER_UPDATE_INFO: "/user/user-update-info",
    USER_UPDATE_PASSWORD: "/user/user-update-password",
    USER_CREATE_PASSWORD: "/user/user-create-password",

    CREATE_COUPON: "/coupon/create-coupon",
    UPDATE_COUPON: "/coupon/update-coupon",
    DELETE_COUPON: "/coupon/delete-coupon",
    GET_ALL_COUPON: "/coupon/get-all-coupon",
    VALIDATE_COUPON: "/coupon/validate-coupon",

    CREATE_ORDER: "/order/create-order",
    GET_USER_ORDERS: "/order/get-user-orders",
    CANCEL_SINGLE_ORDER: "/cancel-order",
    GET_ALL_ORDERS: "/order/get-all-orders",
    UPDATE_ORDER_STATUS: "/order/update-status",
    GET_ORDER_DETAIL: "/order/get-details-order",
    GET_DASHBOARD_STATS: "/order/get-dashboard-stats",

    CREATE_REVIEW: "/review/create-review",
    GET_ALL_REVIEWS: "/review/get-reviews",
    DELETE_REVIEW: "/review/delete-review",
    PIN_REVIEW: "/review/pin-review",
    GET_PIN_REVIEW: "/review/get-pin-reviews",
    SEND_EMAIL_FOR_REVIEWER: "/review/send-email-for-customer",

    CREATE_PROGRAM: "/discount/create-discount",
    GET_CURRENT_PROGRAM: "discount/current-program",
    UPDATE_PROGRAM: "/discount/update-program",
    CANCEL_PROGRAM: "/discount/cancel-program",

    GET_RECENTLY_SEARCH: "/search-history/get-recently-search",
    GET_TOP_SEARCH: "/search-history/get-top-search",
    REMOVE_SEARCH_HISTORY: "/search-history/remove-search-history",

    CREATE_TEMPLATE: "/template/create-template",
    GET_ALL_TEMPLATE: "/template/all-templates",
    UPDATE_TEMPLATE: "/template/update-template",
    DELETE_TEMPLATE: "/template/delete-template",
};
